import numpy as np
import math
p=open("Bit_Plane_Slicing/lena.pgm",'r')
p1=p.readline()
p2=p.readline()
p3=p.readline()
p4=p.readline()
col,row=[int(i) for i in p3.split()]
k=np.zeros((row,col),dtype=int)
k8=np.zeros((row,col),dtype=int)
k7=np.zeros((row,col),dtype=int)
k6=np.zeros((row,col),dtype=int)
k5=np.zeros((row,col),dtype=int)
k4=np.zeros((row,col),dtype=int)
k3=np.zeros((row,col),dtype=int)
k2=np.zeros((row,col),dtype=int)
k1=np.zeros((row,col),dtype=int)
for i in range(row):
    for j in range(col):
        k[i,j]=int(p.readline())

p.close()

q=open("Bit_Plane_Slicing/output.pgm",'w')

q.write(p1)
q.write(p2)
q.write(p3)
q.write(p4)
R=0


for i in range(row):
    for j in range(col):
        if (k[i,j]>=128):
            k8[i,j]=1
            R=k[i,j]-128
            if(R>=64):
                k7[i,j]=1
                R=R-64
                if(R>=32):
                    k6[i,j]=1
                    R=R-32
                    if(R>=16):
                        k5[i,j]=1
                        R=R-16
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                    else:
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                else:
                    if(R>=16):
                        k5[i,j]=1
                        R=R-16
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                    else:
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
            else:
                if(R>=32):
                    k6[i,j]=1
                    R=R-32
                    if(R>=16):
                        k5[i,j]=1
                        R=R-16
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                    else:
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                else:
                    if(R>=16):
                        k5[i,j]=1
                        R=R-16
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                    else:
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
        else:
            if(R>=64):
                k7[i,j]=1
                R=R-64
                if(R>=32):
                    k6[i,j]=1
                    R=R-32
                    if(R>=16):
                        k5[i,j]=1
                        R=R-16
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                    else:
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                else:
                    if(R>=16):
                        k5[i,j]=1
                        R=R-16
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                    else:
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
            else:
                if(R>=32):
                    k6[i,j]=1
                    R=R-32
                    if(R>=16):
                        k5[i,j]=1
                        R=R-16
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                    else:
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                else:
                    if(R>=16):
                        k5[i,j]=1
                        R=R-16
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                    else:
                        if(R>=8):
                            k4[i,j]=1
                            R=R-8
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                        else:
                            if(R>=4):
                                k3[i,j]=1
                                R=R-4
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1
                            else:
                                if(R>=2):
                                    k2[i,j]=1
                                    R=R-2
                                    if(R==1):
                                        k1[i,j]=1
                                else:
                                    k1[i,j]=1            






for i  in range(row):
    for j in range(col):
        
        q.write(f"{128*k8[i,j]+64*k7[i,j]}\n")
        

       
        
       
        

       
q.close()
